/*
 *  ------------------------------------------------------------------
 *  JiveCast
 *  301 Fayetteville St Unit 2301
 *  Raleigh, NC 27601
 *  https://jivecast.com
 *
 *  Copyright (c) 2018-2025 JiveCast. All Rights Reserved.
 *
 *  THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 *  EITHER EXPRESSED OR IMPLIED, INCLUDING, WITHOUT
 *  LIMITATION, WARRANTIES THAT THE PROGRAM IS FREE OF
 *  DEFECTS, MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE OR
 *  NON-INFRINGING. THE ENTIRE RISK AS TO THE QUALITY AND
 *  PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD ANY PART
 *  OF THE PROGRAM PROVE DEFECTIVE IN ANY RESPECT, YOU
 *  (NOT JIVECAST) ASSUME THE COST OF ANY NECESSARY SERVICING,
 *  REPAIR OR CORRECTION. THIS DISCLAIMER OF WARRANTY CONSTITUTES
 *  AN ESSENTIAL PART OF THIS LICENSE. NO USE OF
 *  THE PROGRAM IS AUTHORIZED HEREUNDER EXCEPT
 *  UNDER THIS DISCLAIMER.
 *
 *  ------------------------------------------------------------------
 */

package com.jivecast.webstore.om;

import java.util.List;
import java.util.Vector;

import org.apache.torque.criteria.Criteria;
import org.apache.torque.util.CountHelper;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sat Apr 18 18:43:39 EDT 2020]
 *
 * You should add additional methods to this class to meet the application
 * requirements. This class will only be generated as long as it does not
 * already exist in the output directory.
 */

public class EventLog extends com.jivecast.webstore.om.BaseEventLog {
	/** Serial version */
	private static final long serialVersionUID = 1587249819169L;

	/**
	 * return list of all logs sort from newest to oldest
	 */
	public static List getAllLogs() {
		try {
			Criteria criteria = new Criteria();
			criteria.addAscendingOrderByColumn(EventLogPeer.TX_DATE);
			List results = EventLogPeer.doSelect(criteria);
			return results;
		} catch (Exception e) {
			// Log.info("No logs found.");
			return null;
		}
	}

	/**
	 * Get the event logs using pagination method
	 */
	public static List<EventLog> getAllLogs(int limit, int idx) {
		// int limit = 5;
		List<EventLog> events = new Vector<EventLog>();
		List<Integer> postId = new Vector<Integer>();

		try {
			Criteria criteria = new Criteria();
			// Newest to oldest
			criteria.addDescendingOrderByColumn(EventLogPeer.TX_DATE);
			List<EventLog> history = (List<EventLog>) EventLogPeer.doSelect(criteria);

			// Paginate the results
			int startId = 0;
			int endId = 0;
			int currId = 0;

			// Check index size
			if (history.size() > limit) {
				// Set the start and end ID
				startId = limit * idx;
				endId = startId + limit;
				for (EventLog h : history) {
					if (startId <= currId && currId < endId) {
						events.add(h);
					}
					currId++;
				}

			} else {
				for (EventLog h : history)
					events.add(h);
			}

			return events;
		} catch (Exception e) {
			return null;
		}
	}

	/**
	 * Determine number of pages to show the posts
	 * 
	 * @param product_key
	 * @return
	 */
	public static List<Integer> getEventPages(int limit) {
		try {
			List<Integer> pages = new Vector<Integer>();

			// setup basic criteria
			Criteria criteria = new Criteria();
			criteria.where(EventLogPeer.LOG_ID, 0, Criteria.GREATER_EQUAL);
			criteria.setDistinct();

			CountHelper counter = new CountHelper();
			int count = counter.count(criteria, EventLogPeer.LOG_ID);
			int page_count = (int) Math.ceil(count / limit) + 1;
			for (int i = 0; i < page_count; i++)
				pages.add(i);
			return pages;
		} catch (Exception e) {
			return null;
		}
	}

}
